[package]
name = "zlicenser-server-python"
version = "0.1.0"
edition = "2021"
authors = ["ZAL Analytics <info@zal-analytics.chl>"]
publish = false

[lib]
name = "zlicenser_server_python"
crate-type = ["cdylib"]

[dependencies]
zlicenser-server = { path = "../../" }
pyo3 = { version = "0.29", features = ["extension-module"] }
